import Foundation
import AppKit

/// Checks whether the MITM root CA is trusted by macOS and, when it is not,
/// installs it into the System keychain via a native admin password dialog.
///
/// shade-core writes the CA to Application Support/Shade/ca/ca.crt on first
/// start. Swift handles the trust install so there's no sudo/TTY problem.
enum CertManager {
    private static let certCommonName = "MasterHttpRelayVPN"

    static var caPath: String {
        let base = FileManager.default.urls(
            for: .applicationSupportDirectory, in: .userDomainMask
        )[0]
        return base.appendingPathComponent("Shade/ca/ca.crt").path
    }

    // MARK: - Trust check

    /// Returns true if the CA cert file exists AND macOS considers it trusted.
    static func isTrusted() -> Bool {
        guard FileManager.default.fileExists(atPath: caPath) else { return false }

        // security verify-cert returns 0 ONLY if the certificate is present in
        // a keychain AND marked as trusted for the specified (or default) policy.
        // This is the only reliable way to check if HTTPS interception will work.
        return runSecurity(["verify-cert", "-c", caPath]) == 0
    }

    // MARK: - Install

    enum InstallResult {
        case alreadyTrusted
        case installedOK
        case cancelled
        case failed(String)
    }

    /// Installs the CA cert into the System keychain with an admin prompt.
    /// Safe to call from any async context; blocks until the user responds.
    static func installIfNeeded() async -> InstallResult {
        await ensureCertFileExists()

        guard FileManager.default.fileExists(atPath: caPath) else {
            return .failed("CA cert could not be generated by core.")
        }
        if isTrusted() { return .alreadyTrusted }

        return await installIntoSystemKeychain(removingExisting: false)
    }

    /// Removes all existing MasterHttpRelayVPN certs from user + system
    /// keychains and installs a fresh CA copy into the System keychain.
    static func reinstallFreshCertificate() async -> InstallResult {
        // Delete existing CA files to force the core to generate a BRAND NEW CA if requested.
        // This ensures "Fresh" actually means a fresh certificate, not just a re-install.
        let caFolder = URL(fileURLWithPath: caPath).deletingLastPathComponent().path
        try? FileManager.default.removeItem(atPath: caFolder)

        await ensureCertFileExists()

        guard FileManager.default.fileExists(atPath: caPath) else {
            return .failed("CA cert could not be generated by core.")
        }

        purgeFromUserKeychains()
        return await installIntoSystemKeychain(removingExisting: true)
    }

    static func looksLikeTLSIssue(_ message: String) -> Bool {
        let lowered = message.lowercased()
        return lowered.contains("tls")
            || lowered.contains("ssl")
            || lowered.contains("certificate")
            || lowered.contains("cert")
            || lowered.contains("secure connection")
    }

    private static func installIntoSystemKeychain(removingExisting: Bool) async -> InstallResult {
        // Step 1: Ensure the privileged helper is ready.
        // The helper allows us to run 'security' as root without triggering interaction errors.
        if !SudoPrivilege.isInstalled() {
            do {
                try SudoPrivilege.install()
            } catch {
                return .failed("Failed to install admin helper: \(error.localizedDescription)")
            }
        }

        // Step 2: Use the helper to install the cert.
        // This runs 'sudo -n /usr/local/bin/shade-tun cert-install ...'
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", SudoPrivilege.tunHelperPath, "cert-install", caPath, certCommonName]
        
        let sink = Pipe()
        p.standardOutput = sink
        p.standardError = sink
        
        do {
            try p.run()
            p.waitUntilExit()
            
            if !isTrusted() {
                // If it still failed, the helper might have timed out or had an issue.
                // Fallback to the explicit prompt if necessary, but the helper is usually enough.
                return .failed("Admin helper could not apply trust settings.")
            }
            return .installedOK
        } catch {
            return .failed("Admin helper execution failed: \(error.localizedDescription)")
        }
    }

    // MARK: - Helpers

    private static func runSecurity(_ args: [String]) -> Int32 {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/security")
        p.arguments = args
        let sink = Pipe()
        p.standardOutput = sink
        p.standardError = sink
        do { try p.run(); p.waitUntilExit() } catch { return -1 }
        return p.terminationStatus
    }

    private static func runSecurityOutput(_ args: [String]) -> (Int32, String) {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/security")
        p.arguments = args
        let sink = Pipe()
        p.standardOutput = sink
        p.standardError = sink
        do {
            try p.run()
            p.waitUntilExit()
        } catch {
            return (-1, "")
        }
        let out = String(data: sink.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
        return (p.terminationStatus, out)
    }

    private static func purgeFromUserKeychains() {
        let keychains = userKeychains()
        for keychain in keychains {
            while runSecurity(["delete-certificate", "-c", certCommonName, keychain]) == 0 {
                continue
            }
        }
    }

    private static func userKeychains() -> [String] {
        let (status, out) = runSecurityOutput(["list-keychains", "-d", "user"])
        var items: [String] = []
        if status == 0 {
            for raw in out.split(separator: "\n") {
                var line = raw.trimmingCharacters(in: .whitespacesAndNewlines)
                if line.hasPrefix("\"") && line.hasSuffix("\"") && line.count >= 2 {
                    line.removeFirst()
                    line.removeLast()
                }
                if line.hasPrefix("~/") {
                    line = NSHomeDirectory() + "/" + String(line.dropFirst(2))
                }
                if !line.isEmpty { items.append(line) }
            }
        }

        let defaults = [
            NSHomeDirectory() + "/Library/Keychains/login.keychain-db",
            NSHomeDirectory() + "/Library/Keychains/login.keychain"
        ]
        for path in defaults where !items.contains(path) {
            items.append(path)
        }
        return items
    }

    private static func ensureCertFileExists() async {
        if FileManager.default.fileExists(atPath: caPath) { return }
        
        let arch = currentMachineArch()
        guard let coreURL = resolveCoreBinary(hostArch: arch) else { return }

        let p = Process()
        p.executableURL = coreURL
        p.arguments = ["--install-cert"]
        p.environment = [
            "HOME": NSHomeDirectory(),
            "PATH": "/usr/bin:/bin:/usr/sbin:/sbin"
        ]
        
        // Suppress output so we don't mess with the UI logs prematurely
        p.standardOutput = Pipe()
        p.standardError = Pipe()
        
        try? p.run()
        p.waitUntilExit()
    }

    private static func currentMachineArch() -> String {
        var size = 0
        sysctlbyname("hw.machine", nil, &size, nil, 0)
        var buf = [CChar](repeating: 0, count: size)
        sysctlbyname("hw.machine", &buf, &size, nil, 0)
        let machine = String(cString: buf)
        if machine.hasPrefix("arm") { return "arm64" }
        if machine.hasPrefix("x86") { return "x86_64" }
        return machine
    }

    private static func resolveCoreBinary(hostArch: String) -> URL? {
        let name = "shade-core-\(hostArch)"
        return Bundle.main.url(forResource: name, withExtension: nil)
    }

    private static func shellSingleQuote(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    private static func escape(_ s: String) -> String {
        var out = ""
        for ch in s {
            switch ch {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            default:   out.append(ch)
            }
        }
        return out
    }
}
