import Foundation
import AppKit

/// One-time admin escalation that drops a scoped NOPASSWD sudoers rule + a
/// tiny wrapper script to `/usr/local/bin/shade-tun`. After install, the
/// TUN layer can bring `utun` up/down and tweak routes without prompting.
///
/// The sudoers rule is narrowly scoped to this wrapper (no wildcards), and
/// the wrapper only runs `ifconfig` and `route` with user-provided args that
/// we sanitize in shell.
enum SudoPrivilege {
    static let sudoersPath = "/etc/sudoers.d/shade"
    static let tunHelperPath = "/usr/local/bin/shade-tun"
    static let helperVersion = "1.0.4" // increment when changing the helper

    enum SudoError: LocalizedError {
        case promptCancelled
        case installFailed(String)

        var errorDescription: String? {
            switch self {
            case .promptCancelled:
                return "Admin permission was cancelled. TUN mode needs it once to set up its background helper."
            case .installFailed(let msg):
                return "TUN helper install failed: \(msg)"
            }
        }
    }

    /// True if the helper is installed AND passwordless sudo works against it.
    static func isInstalled() -> Bool { tunHelperReady() }

    static func tunHelperReady() -> Bool {
        let fm = FileManager.default
        guard fm.isExecutableFile(atPath: tunHelperPath),
              fm.fileExists(atPath: sudoersPath)
        else { return false }
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sudo")
        p.arguments = ["-n", tunHelperPath, "--self-check"]
        let out = Pipe()
        p.standardOutput = out
        p.standardError = out
        do {
            try p.run()
            p.waitUntilExit()
            guard p.terminationStatus == 0 else { return false }
            let text = String(data: out.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
                .trimmingCharacters(in: .whitespacesAndNewlines)
            return text == helperVersion
        } catch {
            return false
        }
    }

    static func install() throws {
        let user = NSUserName()

                // Wrapper script: handles "up"/"down" routes and launches tun2socks
                // as root when asked via the "run" action.
        // commands. Keeps dangerous ops inside a single file so the sudoers
        // rule can stay narrow.
        let helperScript = """
        #!/bin/bash
        # Auto-generated by Shade.app. Brings a utun up/down and adjusts routes
        # so the Python proxy layer can tunnel IPv4 through tun2socks.
        set -euo pipefail
        if [ "${1:-}" = "--self-check" ]; then echo "\(helperVersion)"; exit 0; fi
        ACTION="${1:-}"
                if [ "$ACTION" = "run" ]; then
                    BIN="${2:-}"
                    UTUN="${3:-}"
                    PROXY="${4:-}"
                    MTU="${5:-1500}"
                    if [ -z "$BIN" ] || [ -z "$UTUN" ] || [ -z "$PROXY" ]; then
                        echo "usage: $0 run <tun2socks_bin> <utun> <proxy_url> <mtu>" >&2
                        exit 1
                    fi
                    exec "$BIN" -device "$UTUN" -proxy "$PROXY" -mtu "$MTU" -loglevel info
                fi
        PROTECT="${2:-}"
        UTUN="${3:-}"
        MTU="${4:-1500}"
        if [ -z "$ACTION" ] || [ -z "$UTUN" ]; then
          echo "usage: $0 up|down <protect_ip> <utun> <mtu>" >&2
          exit 1
        fi
        GW="$(/sbin/route -n get default 2>/dev/null | /usr/bin/awk '/gateway:/{print $2; exit}')"
        case "$ACTION" in
          up)
            /sbin/ifconfig "$UTUN" 198.18.0.1 198.18.0.2 netmask 255.255.255.0 mtu "$MTU" up 2>/dev/null || true
            if [ -n "$GW" ] && [ -n "$PROTECT" ]; then
              /sbin/route -q add -host "$PROTECT" "$GW" 2>/dev/null || \\
              /sbin/route -q change -host "$PROTECT" "$GW" 2>/dev/null || true
            fi
            /sbin/route -q add -net 0.0.0.0/1 -interface "$UTUN" 2>/dev/null || \\
              /sbin/route -q change -net 0.0.0.0/1 -interface "$UTUN" 2>/dev/null || true
            /sbin/route -q add -net 128.0.0.0/1 -interface "$UTUN" 2>/dev/null || \\
              /sbin/route -q change -net 128.0.0.0/1 -interface "$UTUN" 2>/dev/null || true
            ;;
          down)
            /sbin/route -q delete -net 0.0.0.0/1 -interface "$UTUN" 2>/dev/null || true
            /sbin/route -q delete -net 128.0.0.0/1 -interface "$UTUN" 2>/dev/null || true
            if [ -n "$PROTECT" ]; then
              /sbin/route -q delete -host "$PROTECT" 2>/dev/null || true
            fi
            /sbin/ifconfig "$UTUN" down 2>/dev/null || true
            ;;
          *)
            echo "usage: $0 up|down <protect_ip> <utun> <mtu>" >&2
            exit 1
            ;;
        esac
        """
        let helperB64 = Data(helperScript.utf8).base64EncodedString()

        let sudoersContent = """
        \(user) ALL=(ALL) NOPASSWD: \(tunHelperPath)
        """
        let sudoersB64 = Data(sudoersContent.utf8).base64EncodedString()

        let shell = """
        set -e
        mkdir -p /usr/local/bin
        echo '\(helperB64)' | /usr/bin/base64 -D > '\(tunHelperPath)'
        chown root:wheel '\(tunHelperPath)'
        chmod 755 '\(tunHelperPath)'
        echo '\(sudoersB64)' | /usr/bin/base64 -D > '\(sudoersPath)'
        chown root:wheel '\(sudoersPath)'
        chmod 440 '\(sudoersPath)'
        /usr/sbin/visudo -cf '\(sudoersPath)' >/dev/null
        """

        let appleScriptSource = """
        do shell script "\(escapeForAppleScript(shell))" with administrator privileges with prompt "Shade needs one-time admin permission so it can enable system tunnel mode without asking for your password every time."
        """

        var err: NSDictionary?
        if let script = NSAppleScript(source: appleScriptSource) {
            _ = script.executeAndReturnError(&err)
        }
        if let e = err {
            let code = (e[NSAppleScript.errorNumber] as? Int) ?? 0
            if code == -128 { throw SudoError.promptCancelled }
            let msg = (e[NSAppleScript.errorMessage] as? String) ?? "unknown"
            throw SudoError.installFailed(msg)
        }
        guard isInstalled() else {
            throw SudoError.installFailed("Sudoers rule did not activate — try again.")
        }
    }

    static func uninstall() throws {
        let shell = """
        rm -f '\(sudoersPath)'
        rm -f '\(tunHelperPath)'
        """
        let source = """
        do shell script "\(escapeForAppleScript(shell))" with administrator privileges with prompt "Remove Shade's passwordless TUN helper?"
        """
        var err: NSDictionary?
        if let script = NSAppleScript(source: source) {
            _ = script.executeAndReturnError(&err)
        }
        if let e = err {
            let code = (e[NSAppleScript.errorNumber] as? Int) ?? 0
            if code == -128 { throw SudoError.promptCancelled }
            let msg = (e[NSAppleScript.errorMessage] as? String) ?? "unknown"
            throw SudoError.installFailed(msg)
        }
    }

    private static func escapeForAppleScript(_ s: String) -> String {
        var out = ""
        for ch in s {
            switch ch {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            default: out.append(ch)
            }
        }
        return out
    }
}
